spring:
  redis:
    host: 192.168.10.154
    port: 6379

#Sample
cacheable:
  #Cache names ttl config
  cache-names:
    sample-cache-name-one:
      time-to-live: 60
      unit: SECONDS

    sample-cache-name-two:
      time-to-live: 1
      unit: HOURS
